### ISSUE TITLE
When "rewritePath" is Root (i.e. "/"), then RewriteFilter inserts "" instead of "/"

### ISSUE THREAD

**Issue by maheshkelkar** [lookout/borderpatrol#162]
If we have a ServiceIdentifier as follows:
    {
      "hosts": ["http://localhost:8081"],
      "path": "/good",
      "rewritePath": "/",
      "name": "fun"
    }
For this configuration, any request arriving for the "fun" service i.e. "/good/*", the "RewriteFilter" is supposed to replace "/good" with "/". However it fails to do so.
This is NOT a bug in circe (JSON encoder/decoder) or the code. Its a property of "com.twitter.finagle.http.path.Root".
So we need to add a workaround for that.

**Comment by kgangwani** [comment]
Is there a ticket to implement workaround?

**Comment by kgangwani** [comment]
Saw that #163 fixes this issue. Replied too soon.
