### ISSUE TITLE
Setup github pages for documentation

### ISSUE THREAD

**Issue by trane** [lookout/borderpatrol#35]
We should be publishing our scaladocs to lookout.github.io/borderpatrol/docs

**Comment by rtyler** [comment]
A `gh-pages` branch is all you need for this. [verspaetung](http://hackers.lookout.com/verspaetung/)'s docs are published under hackers.lookout.com and technically lookout.github.io because hooray CNAMEs

**Comment by trane** [comment]
@rtyler thanks a lot, got it all set up now :+1:
