### ISSUE TITLE
Add tut as a dependency during builds

### ISSUE THREAD

**Issue by trane** [lookout/borderpatrol#54]
We want our documentation to stay up-to-date -- it's horrible when it doesn't.

Tut will enforce that our documentation examples compile (this includes requiring imports to be scoped properly).

https://github.com/tpolecat/tut

**Comment by jamescway** [comment]
it looks like tut doesn't parse scaladoc and only really parses markdown/html type of files.  Doobie has a tut dir that has all md files as an example.

**Comment by jamescway** [comment]
checking out sbt-doctest

**Comment by jamescway** [comment]
sbt-doctest generates tests based on the scaladocs and runs with the `test` command.  Maybe it would be easier to maintain a set of MD files, @trane do you have any preference?

**Comment by trane** [comment]
we need sbt-doctest regardless.
i would prefer to have great markdown user docs AND scaladoc.

**Comment by trane** [comment]
let's focus on tut and moving our user docs from scaladoc to markdown, and bettering our user docs.
